default: &default
  adapter: postgresql
  encoding: unicode
  username: abeleon
  password: showmethecode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: instagram_development


test:
  <<: *default
  database: instagram_test


production:
  <<: *default
  database: instagram_production
  username: instagram
  password: <%= ENV['INSTAGRAM_DATABASE_PASSWORD'] %>
